---
# Install and start Nginx on all servers ubuntu and Linux

- name: Install Nginx
  hosts: all
  become: yes

  tasks:

    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started
