---
#In all target server we need to install Nginx and start Nginx
#Name indicates the Description of the playbook
 - name: Install Nginx
   host: all
   become: root

   tasks:
    - name: Install Nginx
      apt: 
      name: nginx
      state: present

    - name: Start Nginx
      service: 
      state: started
      

